### ISSUE TITLE
Better Approach 

### ISSUE THREAD

**Issue by 24js** [MohamadKh75/ShutHub#4]
بهتره اینجوری با محتوا بگیریش که باقیه نوتیفیکیشن ها از بین نره 

```javascript
[...document.querySelectorAll("div.js-notice")]
   .filter(bs => bs.textContent.includes("Due to U.S. trade controls law restrictions"))
   .forEach(bs => bs.style.display = 'none'); // bs for bullshit
```

**Comment by alipiry** [comment]
@24js are you sure it'll hide all of the notifications?

**Comment by 24js** [comment]
@alipiry Yes, Currently I have a notification related to my ssh key it has the same `flash flash-full js-notice flash-warn` class

**Comment by JafarAkhondali** [comment]
@24js Which one is the first notification? SSH or restricted?

**Comment by 24js** [comment]
@JafarAkhondali restricted is first

**Comment by alipiry** [comment]
> @alipiry Yes, Currently I have a notification related to my ssh key it has the same `flash flash-full js-notice flash-warn` class

@24js alright, please reproduce the issue.
Then if you could fix this problem, fix it and create PR. Thanks btw

**Comment by JafarAkhondali** [comment]
@24js His code is also using the first DOM returned from querySelector. So it should be fine

**Comment by 24js** [comment]
I think it doesn't matter anymore, Github added close button to restriction notification, once you close it doesn't show up

**Comment by MoKhajavi75** [comment]
Closing since GitHub added the close button!
